### ISSUE TITLE
snips.toml error 

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAliceSatellite#6]
just reinstalled a satellite. satellite verion is on B1 with a git pull and respeaker 2. I recieved this on start up 

>Dec 13 04:30:50 outdoorSatellite python3[5150]: #033[39m[HotwordDownloadThread]   New hotword received, unpacking...#033[0m
Dec 13 04:30:50 outdoorSatellite python3[5150]: mv: cannot stat 'snips.toml': No such file or directory
Dec 13 04:30:50 outdoorSatellite python3[5150]: #033[39m[HotwordDownloadThread]   Sucessfully installed new hotword #033[1mmycroft-precise#033[0;39m#033[0m

Seems to load and play sound but doesn't trigger the hotword, Not being able to trigger hotword is not a direct result of the above error as far as i know, because the no wakeword is a seperate issue  that just started recently on my satellite... hence the re-install attempt (which didnt fix it ) :)

**Comment by philipp2310** [comment]
snips.toml is gone now - so this error will be gone as well when it is stable again :)
